// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBookingSystem.BookingService.Data;

#nullable disable

namespace TicketBookingSystem.BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260501224353_CabinAvailability")]
    partial class CabinAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBookingSystem.BookingService.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CabinId")
                        .HasColumnType("int");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConvenienceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CruiseId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationPortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Disembarkation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Embarkation")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<string>("JourneyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nights")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingReference")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TicketBookingSystem.BookingService.Models.CabinAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookedCabins")
                        .HasColumnType("int");

                    b.Property<int>("CabinTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CabinTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCabins")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CabinAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 2
                        },
                        new
                        {
                            Id = 7,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 2
                        },
                        new
                        {
                            Id = 8,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 2
                        },
                        new
                        {
                            Id = 9,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 3
                        },
                        new
                        {
                            Id = 10,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 3
                        },
                        new
                        {
                            Id = 11,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 3
                        },
                        new
                        {
                            Id = 12,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 3
                        },
                        new
                        {
                            Id = 13,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 4
                        },
                        new
                        {
                            Id = 14,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 4
                        },
                        new
                        {
                            Id = 15,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 4
                        },
                        new
                        {
                            Id = 16,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 4
                        },
                        new
                        {
                            Id = 17,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 5
                        },
                        new
                        {
                            Id = 18,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 5
                        },
                        new
                        {
                            Id = 19,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 5
                        },
                        new
                        {
                            Id = 20,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 5
                        },
                        new
                        {
                            Id = 21,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 6
                        },
                        new
                        {
                            Id = 22,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 6
                        },
                        new
                        {
                            Id = 23,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 6
                        },
                        new
                        {
                            Id = 24,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 6
                        },
                        new
                        {
                            Id = 25,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 7
                        },
                        new
                        {
                            Id = 26,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 7
                        },
                        new
                        {
                            Id = 27,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 7
                        },
                        new
                        {
                            Id = 28,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 7
                        },
                        new
                        {
                            Id = 29,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 8
                        },
                        new
                        {
                            Id = 30,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 8
                        },
                        new
                        {
                            Id = 31,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 8
                        },
                        new
                        {
                            Id = 32,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 8
                        },
                        new
                        {
                            Id = 33,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 9
                        },
                        new
                        {
                            Id = 34,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 9
                        },
                        new
                        {
                            Id = 35,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 9
                        },
                        new
                        {
                            Id = 36,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 9
                        },
                        new
                        {
                            Id = 37,
                            BookedCabins = 0,
                            CabinTypeId = 1,
                            CabinTypeName = "Interior",
                            TotalCabins = 20,
                            TripId = 10
                        },
                        new
                        {
                            Id = 38,
                            BookedCabins = 0,
                            CabinTypeId = 2,
                            CabinTypeName = "Ocean View",
                            TotalCabins = 15,
                            TripId = 10
                        },
                        new
                        {
                            Id = 39,
                            BookedCabins = 0,
                            CabinTypeId = 3,
                            CabinTypeName = "Balcony",
                            TotalCabins = 10,
                            TripId = 10
                        },
                        new
                        {
                            Id = 40,
                            BookedCabins = 0,
                            CabinTypeId = 4,
                            CabinTypeName = "Suite",
                            TotalCabins = 5,
                            TripId = 10
                        });
                });

            modelBuilder.Entity("TicketBookingSystem.BookingService.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
