// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBookingSystem.CabinService.Data;

#nullable disable

namespace TicketBookingSystem.CabinService.Migrations
{
    [DbContext(typeof(CabinDbContext))]
    [Migration("20260428093832_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinTypeId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.Cabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CabinNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CabinTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DeckNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CabinTypeId");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.CabinImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CabinTypeId");

                    b.ToTable("CabinImages");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.CabinType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerPerson")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CabinTypes");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.Amenity", b =>
                {
                    b.HasOne("TicketBookingSystem.CabinService.Models.CabinType", "CabinType")
                        .WithMany("Amenities")
                        .HasForeignKey("CabinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinType");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.Cabin", b =>
                {
                    b.HasOne("TicketBookingSystem.CabinService.Models.CabinType", "CabinType")
                        .WithMany("Cabins")
                        .HasForeignKey("CabinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinType");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.CabinImage", b =>
                {
                    b.HasOne("TicketBookingSystem.CabinService.Models.CabinType", "CabinType")
                        .WithMany("Images")
                        .HasForeignKey("CabinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabinType");
                });

            modelBuilder.Entity("TicketBookingSystem.CabinService.Models.CabinType", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Cabins");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
